config/routes.rb
# config/routes.rb
PencilIn::Application.routes.draw do
  get 'calendars/create'
  get 'calendars/new'

  resources :sessions, :users, :calendars, :tasks

  post '/tasks/:id/users', to: 'tasks#add_users_task', as: 'add_users_task'
  get '/tasks', to: 'tasks#index'

  root to: 'welcome#index'
  get "/auth/:provider/callback" => 'calendars#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/task.rb
# Task model, for adding new to-dos
class Task < ActiveRecord::Base
  validates :description, :start_time, :duration, presence: true
  validates_inclusion_of :duration, in: 1..180
  has_many :users_tasks, dependent: :destroy
  has_many :users, through: :users_tasks
end

app/controllers/tasks_controller.rb
# Tasks Controller
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :add_users_task]

  # GET /tasks
  def index
    @tasks = current_user.tasks.sort_by { |obj| obj.start_time }
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @temp = []
    5.times do
      @temp << Task.new
    end
    @calendar = current_user.calendar
  end

  # GET /tasks/1/edit
  def edit
  end

  def add_users_task
    friend = User.find_by email: params[:email]
    if friend.present?
      @task.users << friend
      flash[:success] = "Successfully added user #{friend.email}!"
    else
      flash[:failure] = "Error: No record of such email exists."
    end
    redirect_to @task
  end

  # POST /tasks
  def create
    @calendar = current_user.calendar
    add_bedtime(params[:sleep_start], params[:sleep_end])
    params["tasks"].each do |task|
      task_new = Task.new(task_params(task))
      task_new.start_time = next_avail(task_new.duration, @calendar) unless task_new.duration.nil?
      if task_new.save
        current_user.tasks << task_new
        @calendar.events << task_to_event(task_new)
      end
    end
    redirect_to '/tasks'
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def next_avail(mins, cal)
    sorted = cal.events.sort_by { |obj| obj.start }
    sorted.each_with_index do |event, i|
      break unless i + 1 < cal.events.size
      return event.end unless time_difference_minutes(
        sorted[i + 1].start, event.end) < mins
    end
    nil
  end

  def add_bedtime(sleep_start, sleep_end)
    date = DateTime.now.beginning_of_day
    6.times do 
      event = Event.create(
        start: date + Time.parse(sleep_start).seconds_since_midnight.seconds,
        end: date + Time.parse(sleep_end).seconds_since_midnight.seconds,
        calendar_id: current_user.calendar.id)
      date = (date + 1.days).to_datetime
      current_user.calendar.events << event
    end
  end

  def time_difference_minutes(time1, time2)
    ((time1 - time2) / 1.minute).to_i
  end

  def task_to_event(task)
    Event.new(start: task.start_time, end: (task.start_time + task.duration.minutes))
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def task_params(my_params)
    my_params.permit(:description, :start_time, :duration)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<p>
List up to 5 tasks you need to get done this week.
 They will be prioritized from 1-5.</p>

<%= form_tag tasks_path do %>
  <% i = 0 %>
  <% @temp.each do |task| %>
    <%= fields_for 'tasks[]', task do |f| %>
      <div class="field">
        <%= "#{i += 1}." %>
        <%= f.label :description, 'Task description' %>
        <%= f.text_field :description %>
      </div>
      <div class="field">
        <%= f.label :duration, 'Duration (minutes)' %>
        <%= f.number_field :duration %>
      </div>
      </div>
    <% end %>
  <% end %>
  <div class="field">
    <%= label_tag :sleep_end, 'What time do you wake up?' %>
    <%= time_field_tag :sleep_end %>
  </div>
  <div class="field">
    <%= label_tag :sleep_start, 'What time do you go to bed?' %>
    <%= time_field_tag :sleep_start %>
  </div>
  <div class="field">
    <%= hidden_field_tag :user_id, value: current_user.id %><br>
  </div>
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/tasks/confirm.html.erb
<%= @temp.debug %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Start time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<h2>Upcoming</h2>
  <tbody>
    <% current_user.tasks.each do |task| %>
      <% next if task.start_time < DateTime.now %> 
      <tr>
        <td><%= task.description %></td>
        <td><%= task.start_time.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %b %d, %I:%M %p ") %></td>
        <td><%= task.duration %> minutes</td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Delete', task, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %> minutes
</p>

<p>
  <strong>Add a friend:</strong>
  <%= form_tag add_users_task_path do %>
    <div class="field">
      <%= label_tag :email, 'Email' %>
      <%= text_field_tag :email %>
    </div>
    <div class="actions">
      <%= submit_tag 'Add friend' %>
    </div>
  <% end %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>